// More fake secrets
const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE'
const AWS_SECRET_ACCESS_KEY = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
const GH_TOKEN = 'ghp_1234567890abcdefghijklmnopqrstuvwx'
const SLACK_WEBHOOK_URL='https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX';
